#!/usr/bin/env ts-node
/**
 * Map KNS Registry Add Script
 *
 * This script interacts with the Sui blockchain to add an entry into the KNS registry mapping.
 * It constructs, signs, and executes a transaction that calls the `add` function in the KNS ID Map module.
 *
 * Environment Variables:
 *   - KNS_ID_MAP_ID: The Sui object ID for the KNS ID Map. (Required)
 *   - MAP_PACKAGE_ID: The package ID containing the KNS ID Map module. (Required)
 *   - SUI_NETWORK: The Sui network to target ("testnet" or "mainnet"). (Required)
 *   - KNS_TYPE: The Move type argument required for the `add` call. (Required)
 *
 * Command-line Arguments:
 *   <knsObjectId>:      The object ID to add into the KNS registry.
 *   <keyStoreObjectId>: The object ID of the keystore used in the registry.
 *   <rawPrivateKey>:    A base64-encoded raw private key string. This key is typically found in
 *                       ~/.sui/sui_config/sui.keystore (generated by `sui client new-address`).
 *
 * Usage:
 *   ts-node ./map-kns-registry-add.ts <knsObjectId> <keyStoreObjectId> <rawPrivateKey>
 *
 * Example:
 *   ts-node ./map-kns-registry-add.ts "0xabc123..." "0xdef456..." "base64EncodedPrivateKey"
 *
 * Note:
 *   The script decodes the base64-encoded private key, slices off the first byte, and creates an Ed25519 keypair.
 */

import { getFullnodeUrl, SuiClient } from "@mysten/sui/client";
import { Transaction } from "@mysten/sui/transactions";
import { fromBase64 } from "@mysten/bcs";
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import dotenv from 'dotenv';
dotenv.config(); // Load environment variables from .env file

// Retrieve required environment variables.
const knsIdMapId = process.env.KNS_ID_MAP_ID!;
const mapPackageId = process.env.MAP_PACKAGE_ID!;

// Retrieve command-line arguments.
//   <knsObjectId>: The object ID to add into the registry.
const knsObjectId = process.argv[2];
//   <keyStoreObjectId>: The object ID of the keystore that is used in the registry.
const keyStoreObjectId = process.argv[3];
//   <rawPrivateKey>: Base64-encoded raw private key string.
const raw = fromBase64(process.argv[4]);
// Generate an Ed25519 keypair by slicing off the first byte of the raw key.
const keypair = Ed25519Keypair.fromSecretKey(raw.slice(1));

/**
 * Constructs, signs, and executes a transaction to add a KNS registry entry.
 *
 * The function performs the following steps:
 *  1. Initializes a SuiClient instance connected to the fullnode URL for the specified Sui network.
 *  2. Creates a new transaction builder.
 *  3. Constructs a Move call targeting `knsidmap::add` in the specified package.
 *  4. Creates a vector containing the keystore object ID (converted to a pure Move value) to be passed as an argument.
 *  5. Signs and executes the transaction using the provided Ed25519 keypair.
 *  6. Waits for transaction confirmation and logs the transaction details, including any object changes.
 *
 * @returns A promise that resolves when the transaction execution is complete.
 */
async function map_kns_registry() {
    // Initialize the Sui client with the appropriate fullnode URL.
    const client = new SuiClient({
        url: getFullnodeUrl(process.env.SUI_NETWORK! as "testnet" | "mainnet")
    });
    
    // Create a new transaction builder.
    const txb = new Transaction();
    
    // Log the target Move call for debugging.
    console.log(`${mapPackageId}::knsidmap::add`);
    
    // Create a vector argument containing the keystore object ID.
    const vec = txb.makeMoveVec({
        type: "0x2::object::ID",
        elements: [ txb.pure.id(keyStoreObjectId) ]
    });
    
    // Build the Move call transaction to add the registry entry.
    txb.moveCall({
        target: `${mapPackageId}::knsidmap::add`,
        arguments: [
            txb.object(knsIdMapId),
            txb.object(knsObjectId),
            vec,
        ],
        typeArguments: [process.env.KNS_TYPE!],
    });
    
    // Sign and execute the transaction.
    const tx = await client.signAndExecuteTransaction({
        signer: keypair,
        transaction: txb,
        options: {
            showObjectChanges: true,
        }        
    });
    
    // Wait for the transaction confirmation.
    const resp = await client.waitForTransaction({
        digest: tx.digest,
    });
    
    // Filter for any object changes of type "created".
    const created = tx.objectChanges?.filter(change => change.type === "created") ?? [];
    
    // Log transaction details, any created objects, and the transaction response.
    console.log(tx);
    console.log(created);
    console.log(resp);
}

// Execute the registry add function.
map_kns_registry();
