#!/usr/bin/env ts-node
/**
 * Map KNS Registry Update Script
 *
 * This script interacts with the Sui blockchain to update an entry in the KNS registry mapping.
 * It constructs and signs a transaction to call the `update` function in the KNS ID Map module.
 *
 * Environment Variables:
 *   - KNS_ID_MAP_ID: The Sui object ID for the KNS ID Map (required).
 *   - MAP_PACKAGE_ID: The package ID that contains the KNS ID Map module (required).
 *   - SUI_NETWORK: The Sui network to target ("testnet" or "mainnet") (required).
 *   - KNS_TYPE: The Move type argument required by the update function (required).
 *
 * Command-line Arguments:
 *   <knsObjectId>:      The object ID in the KNS registry to update.
 *   <keyStoreObjectId>: The object ID of the keystore that will be used in the update.
 *   <rawPrivateKey>:    A base64-encoded private key string. This key is typically found in
 *                       the file ~/.sui/sui_config/sui.keystore (generated by `sui client new-address`).
 *
 * Usage:
 *   ts-node ./map-kns-registry-update.ts <knsObjectId> <keyStoreObjectId> <rawPrivateKey>
 *
 * Example:
 *   ts-node ./map-kns-registry-update.ts "0xabc123..." "0xdef456..." "base64EncodedPrivateKey"
 *
 * Note:
 *   - The script decodes the base64-encoded private key, slices off the first byte, and generates an Ed25519 keypair.
 */

import { getFullnodeUrl, SuiClient } from "@mysten/sui/client";
import { Transaction } from "@mysten/sui/transactions";
import { fromBase64 } from "@mysten/bcs";
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import dotenv from 'dotenv';
dotenv.config(); // Load environment variables from .env file

// Environment variables
const knsIdMapId = process.env.KNS_ID_MAP_ID!;
const mapPackageId = process.env.MAP_PACKAGE_ID!;

// Command-line arguments:
//   - knsObjectId: The KNS object ID to update in the registry.
const knsObjectId = process.argv[2];
//   - keyStoreObjectId: The object ID from the keystore to be used in the update.
const keyStoreObjectId = process.argv[3];
//   - rawPrivateKey: Base64-encoded private key from the SUI keystore.
const raw = fromBase64(process.argv[4]);
// Generate an Ed25519 keypair from the provided raw private key (slicing off the first byte)
const keypair = Ed25519Keypair.fromSecretKey(raw.slice(1));

/**
 * Constructs, signs, and executes a transaction to update a KNS registry entry.
 *
 * The function performs the following steps:
 *  1. Creates a SuiClient instance connected to the specified Sui network.
 *  2. Builds a new transaction with a Move call targeting `knsidmap::update` from the MAP_PACKAGE_ID module.
 *  3. Constructs a vector containing the keystore object ID (as a pure Move value) to be passed as an argument.
 *  4. Signs and executes the transaction using the provided Ed25519 keypair.
 *  5. Waits for transaction confirmation and logs the transaction details and any created objects.
 *
 * @returns A promise that resolves when the transaction execution is complete.
 */
async function map_kns_registry() {
    // Initialize the Sui client with the fullnode URL for the specified network.
    const client = new SuiClient({
        url: getFullnodeUrl(process.env.SUI_NETWORK! as "testnet" | "mainnet")
    });
    
    // Create a new transaction builder.
    const txb = new Transaction();
    
    // Log the target Move call for debugging purposes.
    console.log(`${mapPackageId}::knsidmap::update`);
    
    // Create a vector argument containing the keystore object ID.
    const vec = txb.makeMoveVec({ 
        type: "0x2::object::ID", 
        elements: [ txb.pure.id(keyStoreObjectId) ] 
    });
    
    // Construct the Move call for updating the KNS registry.
    txb.moveCall({
        target: `${mapPackageId}::knsidmap::update`,
        arguments: [
            txb.object(knsIdMapId),
            txb.object(knsObjectId),
            vec,
        ],
        typeArguments: [process.env.KNS_TYPE!],
    });
    
    // Sign and execute the transaction.
    const tx = await client.signAndExecuteTransaction({
        signer: keypair,
        transaction: txb,
        options: {
            showObjectChanges: true,
        }        
    });
    
    // Wait for the transaction to be confirmed.
    const resp = await client.waitForTransaction({
        digest: tx.digest,
    });
    
    // Filter any object changes of type "created" from the transaction.
    const created = tx.objectChanges?.filter(change => change.type === "created") ?? [];
    
    // Log the transaction, created objects, and the transaction response.
    console.log(tx);
    console.log(created);
    console.log(resp);   
}

// Execute the registry update function.
map_kns_registry();
