#!/usr/bin/env ts-node
/**
 * Map KNS Registry Remove Script
 *
 * This script interacts with the Sui blockchain to remove a KNS registry mapping.
 * It constructs and signs a transaction to call the `remove` function in the KNS ID Map module.
 *
 * Environment Variables:
 *   - KNS_ID_MAP_ID: The Sui object ID for the KNS ID Map.
 *   - MAP_PACKAGE_ID: The package ID containing the KNS ID Map module.
 *   - SUI_NETWORK: The Sui network to target ("testnet" or "mainnet").
 *   - KNS_TYPE: The Move type argument required for the call.
 *
 * Command-line Arguments:
 *   <knsObjectId>: The object ID from the KNS registry to remove.
 *   <rawPrivateKey>: A base64-encoded raw private key. This key is typically found in the file
 *                    at ~/.sui/sui_config/sui.keystore, generated by `sui client new-address`.
 *
 * Usage:
 *   ts-node ./map-kns-registry-remove.ts <knsObjectId> <rawPrivateKey>
 *
 * Example:
 *   ts-node ./map-kns-registry-remove.ts "0xabc123..." "base64EncodedPrivateKey"
 *
 * Note:
 *   - The private key is provided as a base64 string and the script removes the first byte
 *     before generating an Ed25519 keypair.
 */

import { getFullnodeUrl, SuiClient } from "@mysten/sui/client";
import { Transaction } from "@mysten/sui/transactions";
import { fromBase64 } from "@mysten/bcs";
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import dotenv from 'dotenv';

dotenv.config(); // Load environment variables from .env file

// Environment variables
const knsIdMapId = process.env.KNS_ID_MAP_ID!;
const mapPackageId = process.env.MAP_PACKAGE_ID!;

// Command-line arguments:
//   - knsObjectId: The KNS object ID to remove from the registry.
const knsObjectId = process.argv[2];
//   - rawPrivateKey: Base64-encoded private key from the SUI keystore.
const raw = fromBase64(process.argv[3]);
// Generate an Ed25519 keypair from the provided raw private key (slicing off the first byte)
const keypair = Ed25519Keypair.fromSecretKey(raw.slice(1));

/**
 * Constructs, signs, and executes a transaction to remove a KNS registry entry.
 *
 * The function performs the following steps:
 *  1. Creates a SuiClient instance connected to the specified Sui network fullnode.
 *  2. Constructs a new transaction with a Move call targeting `knsidmap::remove`
 *     from the MAP_PACKAGE_ID module.
 *  3. Signs and executes the transaction using the provided keypair.
 *  4. Waits for the transaction confirmation and logs the transaction details and any created objects.
 *
 * @returns A promise that resolves once the transaction is executed.
 */
async function map_kns_registry() {
  // Initialize a SuiClient instance with the fullnode URL for the specified network.
  const client = new SuiClient({
    url: getFullnodeUrl(process.env.SUI_NETWORK! as "testnet" | "mainnet"),
  });
  
  // Create a new transaction builder.
  const txb = new Transaction();
  
  // Log the target Move call for debugging purposes.
  console.log(`${mapPackageId}::knsidmap::remove`);
  
  // Construct the Move call transaction.
  txb.moveCall({
    target: `${mapPackageId}::knsidmap::remove`,
    arguments: [
      txb.object(knsIdMapId),
      txb.object(knsObjectId)
    ],
    typeArguments: [process.env.KNS_TYPE!],
  });

  // Sign and execute the transaction.
  const tx = await client.signAndExecuteTransaction({
    signer: keypair,
    transaction: txb,
    options: {
      showObjectChanges: true,
    }
  });

  // Wait for the transaction confirmation.
  const resp = await client.waitForTransaction({
    digest: tx.digest,
  });

  // Extract any object changes of type "created".
  const created = tx.objectChanges?.filter(change => change.type === "created") ?? [];
  
  // Log the full transaction details, any created objects, and the transaction response.
  console.log(tx);
  console.log(created);
  console.log(resp);
}

// Execute the registry removal function.
map_kns_registry();
